BrandonAinsworth/FitLit

docs/pull-request-template.md, src/UserRepository.js, test/UserRepository-test.js
Create a pull request template
Create the UserRepository Class
Create UserRepository class related tests
Line 1 of pull-request-template.md
Line 2 of UserRepository.js
Line 5 of UserRepository-test.js
=> Feature user repo class

src/User.js, test/User-test.js, test/UserRepository-test.js
Adds User class and tests sufficient for Iteration 1
From User-tests
Use npm test
=> Feature user class

src/UserRepository.js, src/apiCalls.js, src/scripts.js
We added all fetch functions to the `apiCalls.js` file and imported those functions into the `scripts.js` file. We also updated `UserRepository` class's property for `this.usersData` to access the correct property of the object.
`src/apiCalls.js`
This completes iteration 2 of the project spec sheet.
=> Add API calls and import to scripts.js

back/UserRepository-test.js, src/Hydration.js, src/UserRepository.js, src/apiCalls.js, src/scripts.js, test/Hydration-test.js, test/Sample-data.js, test/UserRepository-test.js
Add the Hydration class declaration
Revise the tests for User and UserRepository
Line 619 of the UserRepository-test.js
=> Feature hydration class

src/Hydration.js, test/Hydration-test.js
Added tests for the Hydration class as well as the constructor properties.
We also removed all of the user data and user global variables we declared in the hook. We realized we aren't going to need that information to run the tests, because all methods for Hydration will be called within the User class.
Hydration-test.js and then move to the Hydration.js file.
=> Add hydration test and class functionality

src/User.js, test/Hydration-test.js, test/User-test.js
Adds all the functionality for calculating a specific user's all time daily consumption, daily ounces consumed, and weekly ounces consumed.
User-test.js
User.js
Hydration-test (only removed an unused import from this file)
=> Feature user hydration methods

dist/index.html, src/Hydration.js, src/User.js, src/apiCalls.js, src/css/styles.css, src/scripts.js
Adds html for Hydration dashboard display
Adds weekly water consumption to the DOM
Small refactors and console log removal
1. index.html
2. scripts.js
3. apiCalls.js
4. User.js
5. Hydration.js
6. styles.css
=> Feature hydration dashboard

src/Sleep.js, test/Sleep-test.js
Adds all tests to the Sleep-test.js file.
Adds Sleep class constructor and functions to pass tests.
Sleep-test.js
Sleep.js
=> Feature sleep class

dist/index.html, src/User.js, src/apiCalls.js, src/css/styles.css, src/scripts.js
Completes Iteration 4 by adding sleep data to the DOM
Start from the DOM!
NPM start and check the website.
=> Features dashboard sleep

dist/index.html, src/Hydration.js, src/User.js, src/scripts.js, test/Hydration-test.js, test/Sample-hydration-data.js, test/Sample-sleep-data.js, test/Sample-user-data.js, test/Sleep-test.js, test/User-test.js
Refactors getData
Refactors thisWeeklySleepData to eliminate the use of the villainous for loop
Add a .catch for proper error handling
at getData
All tests will work normally, testing the catch can be accomplished by breaking the fetch
These changes are implemented feedback from our PM Heather
=> Feature feedback

src/Activity.js, test/Activity-test.js, test/Sample-activity-data.js
Adds Activity.js, Sample-activity-data.js, and Activity-test.js files
1. Activity-test.js
2. Sample-activity-data.js
3. Activity.js
=> Feature activity data

dist/index.html, src/Activity.js, src/User.js, src/css/styles.css, src/scripts.js, test/Activity-test.js, test/Sample-user-data.js, test/User-test.js
Adds all activity functionality and methods for data model.
Add HTML for activity data to be displayed on the DOM.
Updates tests associated with the Activity class and User class.
=> Feature activity

src/apiCalls.js
Updates the apiCalls.js file with new api URLs.
Everyone was using the same exact endpoints for Part One. This is typically how things work, but can cause some headache when implementing types of requests other than GET. In this part of the project, you will start making POST requests. Creating a local server instead of using the hosted (deployed) one, gives everyone their own version of the APIs and decreases an overload of new data getting sent.
=> Update fetch request with new api url

src/User.js, src/scripts.js
Adds the total daily step count for a single user to the DOM.
=> Add daily step count for a single user to dashboard

dist/index.html, src/apiCalls.js, src/css/styles.css, src/scripts.js
Adds activity data to DOM
Adds POST for hydration
=> Feature activity dashboard

dist/index.html, src/apiCalls.js, src/css/styles.css, src/scripts.js
Create the ability to POST Hydration data to the local server.
=> Feature api update

dist/index.html, src/apiCalls.js, src/scripts.js
Add activity POST functionality
scripts.js
apiCalls.js
=> Feature activity post

src/apiCalls.js, src/scripts.js
POST new information for sleep input form
Clear input forms for Hydration and Sleep
scripts.js
apiCalls.js
Submit information via the forms on the dashboard and observe results displayed
=> Features sleep post

src/scripts.js
Updates the data types from the user input fields to match the required data types of the POST request.
Removes no-longer-needed console.logs
=> Feature bug fixes

src/apiCalls.js, src/scripts.js
Add CheckForErrors to the fetch calls
Remove comments for error handling not implemented
apiCalls.js
scripts.js
=> Add error handling to fetch calls and remove unnecessary comments
